version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "master"
    versioning-strategy: "increase"
    commit-message:
      prefix: "chore"
    allow:
      - dependency-type: "direct"
      - dependency-type: "indirect"
    labels:
      - "dependencies"
    reviewers:
      - "yijiaow"
